import type {
  ExpenseListItem,
  PurchaseOrderListItem,
  PurchasingReferenceData,
  SupplierListItem,
} from "./schemas";

export const demoSuppliers: SupplierListItem[] = [
  {
    id: "sup_demo_arc",
    supplierCode: "S-ARC00001",
    name: "Arc Supply Co.",
    contactName: "Noor Siddiqui",
    email: "orders@arc.example",
    phone: "+92 21 555 0160",
    address: "Korangi Industrial Area, Karachi",
    taxNumber: "PK-DEMO-10294",
    paymentTerms: "Net 30",
    notes: "Primary apparel and packaging supplier.",
    status: "active",
    version: 2,
    createdAt: "2025-02-10T09:00:00.000Z",
  },
  {
    id: "sup_demo_harbor",
    supplierCode: "S-HBR00002",
    name: "Harbor Wholesale",
    contactName: "Umair Khan",
    email: "sales@harbor.example",
    phone: "+92 21 555 0162",
    address: "SITE Area, Karachi",
    taxNumber: "PK-DEMO-11820",
    paymentTerms: "50% advance",
    notes: "Footwear and accessories.",
    status: "active",
    version: 1,
    createdAt: "2025-09-18T09:00:00.000Z",
  },
];

export const demoPurchasingReference: PurchasingReferenceData = {
  currency: "PKR",
  stores: [
    { id: "demo-store", code: "DT", name: "Downtown" },
    { id: "demo-west", code: "WH", name: "West Harbor" },
  ],
  expenseCategories: [
    { id: "expcat_utilities", name: "Utilities" },
    { id: "expcat_maintenance", name: "Maintenance" },
    { id: "expcat_transport", name: "Transport" },
    { id: "expcat_marketing", name: "Marketing" },
  ],
  suppliers: demoSuppliers.map((supplier) => ({
    id: supplier.id,
    supplierCode: supplier.supplierCode,
    name: supplier.name,
  })),
  variants: [
    {
      id: "var_demo_kurta",
      productId: "prd_demo_kurta",
      productName: "Classic Cotton Kurta",
      name: "Default",
      sku: "CR-APP-001",
      costMinor: 280_000,
    },
    {
      id: "var_demo_sneaker",
      productId: "prd_demo_sneaker",
      productName: "Everyday Canvas Sneaker",
      name: "Default",
      sku: "CR-FWT-001",
      costMinor: 410_000,
    },
  ],
};

export const demoPurchaseOrders: PurchaseOrderListItem[] = [
  {
    id: "pur_demo_1",
    purchaseOrderNumber: "PO-000314",
    supplierId: "sup_demo_arc",
    supplierCode: "S-ARC00001",
    supplierName: "Arc Supply Co.",
    storeId: "demo-store",
    storeName: "Downtown",
    expectedDeliveryDate: "2026-08-22",
    currency: "PKR",
    status: "approved",
    lines: [
      {
        lineId: "pol_demo_1",
        productId: "prd_demo_kurta",
        variantId: "var_demo_kurta",
        productName: "Classic Cotton Kurta",
        variantName: "Default",
        sku: "CR-APP-001",
        orderedQuantity: 40,
        receivedQuantity: 0,
        unitCostMinor: 280_000,
        taxRateBps: 0,
        subtotalMinor: 11_200_000,
        taxMinor: 0,
        totalMinor: 11_200_000,
      },
    ],
    subtotalMinor: 11_200_000,
    taxMinor: 0,
    totalMinor: 11_200_000,
    version: 3,
    createdAt: "2026-08-14T09:00:00.000Z",
  },
  {
    id: "pur_demo_2",
    purchaseOrderNumber: "PO-000313",
    supplierId: "sup_demo_harbor",
    supplierCode: "S-HBR00002",
    supplierName: "Harbor Wholesale",
    storeId: "demo-west",
    storeName: "West Harbor",
    expectedDeliveryDate: "2026-08-17",
    currency: "PKR",
    status: "partially_received",
    lines: [
      {
        lineId: "pol_demo_2",
        productId: "prd_demo_sneaker",
        variantId: "var_demo_sneaker",
        productName: "Everyday Canvas Sneaker",
        variantName: "Default",
        sku: "CR-FWT-001",
        orderedQuantity: 24,
        receivedQuantity: 12,
        unitCostMinor: 410_000,
        taxRateBps: 0,
        subtotalMinor: 9_840_000,
        taxMinor: 0,
        totalMinor: 9_840_000,
      },
    ],
    subtotalMinor: 9_840_000,
    taxMinor: 0,
    totalMinor: 9_840_000,
    version: 4,
    createdAt: "2026-08-10T09:00:00.000Z",
  },
];

export const demoExpenses: ExpenseListItem[] = [
  {
    id: "exp_demo_1",
    expenseNumber: "EXP-000481",
    storeId: "demo-store",
    storeName: "Downtown",
    category: "Utilities",
    vendor: "K-Electric",
    expenseDate: "2026-08-14",
    amountMinor: 184_200,
    currency: "PKR",
    notes: "August electricity bill",
    receiptUrl: "",
    status: "approved",
    decisionNote: "Matched to statement.",
    version: 2,
    createdAt: "2026-08-14T09:00:00.000Z",
  },
  {
    id: "exp_demo_2",
    expenseNumber: "EXP-000482",
    storeId: "demo-west",
    storeName: "West Harbor",
    category: "Maintenance",
    vendor: "Coastal Repairs",
    expenseDate: "2026-08-16",
    amountMinor: 72_500,
    currency: "PKR",
    notes: "Front shutter service",
    receiptUrl: "",
    status: "submitted",
    decisionNote: "",
    version: 1,
    createdAt: "2026-08-16T09:00:00.000Z",
  },
];
