import type { TenantSettingsProjection } from "./schemas";

export const demoTenantSettings: TenantSettingsProjection = {
  businessName: "Northstar Goods",
  legalName: "Northstar Goods (Private) Limited",
  supportEmail: "hello@northstar.example",
  phone: "+92 21 555 0100",
  address: "Shahrah-e-Faisal, Karachi",
  locale: "en-PK",
  timezone: "Asia/Karachi",
  currency: "PKR",
  planKey: "growth",
  version: 3,
  operationSettings: {
    defaultTaxRateBps: 0,
    pricesIncludeTax: false,
    receiptPrefix: "SALE",
    returnPrefix: "RET",
    purchasePrefix: "PO",
    expensePrefix: "EXP",
    allowNegativeStock: false,
    version: 2,
  },
  integrations: {
    googleOAuth: true,
    stripe: true,
    cloudinary: true,
    email: true,
  },
  stores: [
    {
      id: "demo-store",
      code: "DT",
      name: "Downtown",
      timezone: "Asia/Karachi",
      address: "Clifton, Karachi",
      status: "active",
      version: 2,
      createdAt: "2025-01-10T09:00:00.000Z",
    },
    {
      id: "demo-west",
      code: "WH",
      name: "West Harbor",
      timezone: "Asia/Karachi",
      address: "DHA, Karachi",
      status: "active",
      version: 1,
      createdAt: "2025-07-11T09:00:00.000Z",
    },
  ],
  storeLimit: 3,
  pendingDataRequests: [],
};
