import type { ProductDetail, ProductListItem } from "./schemas";
import { getDemoTagOptions } from "@/modules/tags/demo-data";
import { getDemoUnitOptions } from "@/modules/units/demo-data";

const demoProductTagIds: Record<string, string[]> = {
  prd_growth_suite: ["tag_featured", "tag_new_arrival"],
  prd_commerce_pro: ["tag_featured"],
  prd_analytics: ["tag_low_margin"],
  prd_content: ["tag_new_arrival"],
  prd_devices: ["tag_featured", "tag_seasonal"],
  prd_receipts: ["tag_low_margin"],
  prd_launch: ["tag_new_arrival", "tag_seasonal"],
  prd_loyalty: ["tag_featured"],
};

const demoProductRecords: readonly Omit<
  ProductListItem,
  "tagIds" | "primaryImage"
>[] = [
  {
    id: "prd_growth_suite",
    name: "Growth Suite",
    subtitle: "Annual operations bundle",
    sku: "GS-ANNUAL",
    slug: "growth-suite",
    priceMinor: 124000,
    currency: "USD",
    stock: 248,
    reorderLevel: 40,
    category: "Software",
    status: "active",
    views: 12840,
    revenueMinor: 24840000,
    imageTone: "ink",
  },
  {
    id: "prd_commerce_pro",
    name: "Commerce Pro",
    subtitle: "Team commerce plan",
    sku: "CP-TEAM",
    slug: "commerce-pro",
    priceMinor: 78000,
    currency: "USD",
    stock: 512,
    reorderLevel: 60,
    category: "Software",
    status: "active",
    views: 9430,
    revenueMinor: 18020000,
    imageTone: "sky",
  },
  {
    id: "prd_analytics",
    name: "Analytics Add-on",
    subtitle: "Reporting extension",
    sku: "AN-PRO",
    slug: "analytics-add-on",
    priceMinor: 32000,
    currency: "USD",
    stock: 24,
    reorderLevel: 35,
    category: "Extensions",
    status: "active",
    views: 6120,
    revenueMinor: 7420000,
    imageTone: "slate",
  },
  {
    id: "prd_support",
    name: "Support Desk",
    subtitle: "Managed service workflow",
    sku: "SD-TEAM",
    slug: "support-desk",
    priceMinor: 42000,
    currency: "USD",
    stock: null,
    reorderLevel: 0,
    category: "Services",
    status: "draft",
    views: 3240,
    revenueMinor: 0,
    imageTone: "berry",
  },
  {
    id: "prd_media",
    name: "Media Vault",
    subtitle: "Secure storage package",
    sku: "MV-100",
    slug: "media-vault",
    priceMinor: 21000,
    currency: "USD",
    stock: 0,
    reorderLevel: 20,
    category: "Storage",
    status: "archived",
    views: 2810,
    revenueMinor: 1800000,
    imageTone: "sand",
  },
  {
    id: "prd_content",
    name: "Content Studio",
    subtitle: "Creator workspace",
    sku: "CS-PRO",
    slug: "content-studio",
    priceMinor: 36000,
    currency: "USD",
    stock: 86,
    reorderLevel: 20,
    category: "Templates",
    status: "active",
    views: 4520,
    revenueMinor: 5210000,
    imageTone: "sky",
  },
  {
    id: "prd_starter",
    name: "Starter Catalog",
    subtitle: "Curated entry package",
    sku: "SC-BASE",
    slug: "starter-catalog",
    priceMinor: 9900,
    currency: "USD",
    stock: 1204,
    reorderLevel: 100,
    category: "Templates",
    status: "active",
    views: 7920,
    revenueMinor: 6140000,
    imageTone: "slate",
  },
  {
    id: "prd_onboarding",
    name: "Priority Onboarding",
    subtitle: "Professional setup service",
    sku: "PO-SETUP",
    slug: "priority-onboarding",
    priceMinor: 180000,
    currency: "USD",
    stock: null,
    reorderLevel: 0,
    category: "Services",
    status: "active",
    views: 1120,
    revenueMinor: 9420000,
    imageTone: "mint",
  },
  {
    id: "prd_brand",
    name: "Brand System",
    subtitle: "Identity template library",
    sku: "BS-240",
    slug: "brand-system",
    priceMinor: 24000,
    currency: "USD",
    stock: 73,
    reorderLevel: 15,
    category: "Templates",
    status: "active",
    views: 3680,
    revenueMinor: 3980000,
    imageTone: "berry",
  },
  {
    id: "prd_devices",
    name: "Counter Kit",
    subtitle: "Retail hardware bundle",
    sku: "CK-HW2",
    slug: "counter-kit",
    priceMinor: 89000,
    currency: "USD",
    stock: 12,
    reorderLevel: 18,
    category: "Hardware",
    status: "active",
    views: 2410,
    revenueMinor: 6670000,
    imageTone: "ink",
  },
  {
    id: "prd_receipts",
    name: "Receipt Printer",
    subtitle: "Quiet thermal printer",
    sku: "RP-80",
    slug: "receipt-printer",
    priceMinor: 18900,
    currency: "USD",
    stock: 46,
    reorderLevel: 12,
    category: "Hardware",
    status: "active",
    views: 1980,
    revenueMinor: 2840000,
    imageTone: "sand",
  },
  {
    id: "prd_launch",
    name: "Launch Playbook",
    subtitle: "Store opening templates",
    sku: "LP-DIGI",
    slug: "launch-playbook",
    priceMinor: 7900,
    currency: "USD",
    stock: 780,
    reorderLevel: 50,
    category: "Templates",
    status: "draft",
    views: 840,
    revenueMinor: 0,
    imageTone: "mint",
  },
  {
    id: "prd_audit",
    name: "Audit Export",
    subtitle: "Compliance-ready data pack",
    sku: "AE-PRO",
    slug: "audit-export",
    priceMinor: 29000,
    currency: "USD",
    stock: 144,
    reorderLevel: 25,
    category: "Extensions",
    status: "active",
    views: 2090,
    revenueMinor: 2290000,
    imageTone: "ink",
  },
  {
    id: "prd_training",
    name: "Team Training",
    subtitle: "Live operations workshop",
    sku: "TT-LIVE",
    slug: "team-training",
    priceMinor: 95000,
    currency: "USD",
    stock: null,
    reorderLevel: 0,
    category: "Services",
    status: "active",
    views: 1280,
    revenueMinor: 4750000,
    imageTone: "sky",
  },
  {
    id: "prd_scanner",
    name: "Pocket Scanner",
    subtitle: "Bluetooth barcode reader",
    sku: "PS-BT1",
    slug: "pocket-scanner",
    priceMinor: 12900,
    currency: "USD",
    stock: 0,
    reorderLevel: 15,
    category: "Hardware",
    status: "active",
    views: 1750,
    revenueMinor: 1940000,
    imageTone: "slate",
  },
  {
    id: "prd_loyalty",
    name: "Loyalty Toolkit",
    subtitle: "Retention campaign pack",
    sku: "LT-PLUS",
    slug: "loyalty-toolkit",
    priceMinor: 15900,
    currency: "USD",
    stock: 226,
    reorderLevel: 30,
    category: "Extensions",
    status: "active",
    views: 3320,
    revenueMinor: 3680000,
    imageTone: "berry",
  },
];

export const demoProducts: readonly ProductListItem[] = demoProductRecords.map(
  (product) => ({
    ...product,
    tagIds: demoProductTagIds[product.id] ?? [],
    primaryImage: null,
  }),
);

export function getDemoProductDetail(productId: string): ProductDetail | null {
  const product = demoProducts.find((item) => item.id === productId);
  if (!product) return null;
  const tagOptions = getDemoTagOptions();
  const unit = getDemoUnitOptions()[0] ?? null;
  return {
    ...product,
    type: product.id === "prd_growth_suite" ? "variant" : "simple",
    unitId: unit?.id ?? null,
    unit,
    tags: product.tagIds.flatMap((tagId) => {
      const tag = tagOptions.find((option) => option.id === tagId);
      return tag ? [tag] : [];
    }),
    version: 1,
    createdAt: "2026-01-08T09:00:00.000Z",
    updatedAt: "2026-08-12T14:30:00.000Z",
    images: [],
    optionGroups:
      product.id === "prd_growth_suite"
        ? [
            {
              id: "opt_demo_license",
              name: "License",
              status: "active",
              values: [
                { id: "val_demo_team", label: "Team" },
                { id: "val_demo_business", label: "Business" },
              ],
              activeVariantCount: 2,
            },
          ]
        : [],
    variants: [
      {
        id: `${product.id}_default`,
        name: "Default",
        sku: product.sku,
        priceMinor: product.priceMinor,
        currency: product.currency,
        status: "active",
        isDefault: true,
        optionValues: [],
        authorizedStock: product.stock ?? 0,
        version: 1,
      },
      ...(product.id === "prd_growth_suite"
        ? [
            {
              id: "var_demo_team",
              name: "Team",
              sku: "GS-TEAM",
              priceMinor: 78000,
              currency: product.currency,
              status: "active" as const,
              isDefault: false,
              optionValues: [
                {
                  optionId: "opt_demo_license",
                  optionName: "License",
                  valueId: "val_demo_team",
                  valueLabel: "Team",
                },
              ],
              authorizedStock: 0,
              version: 1,
            },
            {
              id: "var_demo_business",
              name: "Business",
              sku: "GS-BUSINESS",
              priceMinor: 149000,
              currency: product.currency,
              status: "active" as const,
              isDefault: false,
              optionValues: [
                {
                  optionId: "opt_demo_license",
                  optionName: "License",
                  valueId: "val_demo_business",
                  valueLabel: "Business",
                },
              ],
              authorizedStock: 0,
              version: 1,
            },
          ]
        : []),
    ],
    inventory:
      product.stock === null
        ? []
        : [
            {
              storeId: "store_demo",
              storeName: "Downtown",
              storeCode: "MAIN",
              quantity: product.stock,
            },
          ],
  };
}

export const productTrend = [
  { label: "Aug 10", views: 3260, revenue: 28200 },
  { label: "Aug 11", views: 3480, revenue: 30100 },
  { label: "Aug 12", views: 3410, revenue: 33800 },
  { label: "Aug 13", views: 3820, revenue: 36900 },
  { label: "Aug 14", views: 4010, revenue: 35100 },
  { label: "Aug 15", views: 4370, revenue: 41200 },
  { label: "Aug 16", views: 4620, revenue: 46800 },
] as const;
